version: '3'
services:
  afisha_api:
    build:
      context: shop_api
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "7001:8000"
  afisha_db:
    image: 'postgres:14'
    environment:
      - POSTGRES_DB=afisha_db
      - POSTGRES_USER=db_afisha_user
      - POSTGRES_PASSWORD=123
    volumes:
      - 'afisha-datda:/var/lib/postgresql/data'
volumes:
  afisha-data:
